---
title: Programation facile au Cegep
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  unecollection:
    title: UneCollection
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
